project:
  type: website

website:
  title: "eosense-tutorial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - tutorial.qmd
      - comparison.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

author: Joseph Gaudard
